### ISSUE TITLE
Fine Tune Colab, Can't Load Model Error

### ISSUE THREAD

**Issue by Marcus-Arcadius** [corolla-johnson/mkultra#3]
![image](https://user-images.githubusercontent.com/78793842/125065619-602b6c80-e0f5-11eb-80fd-7451bb05a91d.png)

**Comment by corolla-johnson** [comment]
This notebook was sort of written under the assumption that you'd have an fp16 model already uploaded to your Drive, but I suppose it'd be a lot better if it were plug-and-play. For now, I've added a magnet link to finetuneanon's gpt-neo-2.7B-halved, but I'll have a look at setting it up to run out of the box with Huggingface gpt2 and a book from Project Gutenberg.

**Comment by Marcus-Arcadius** [comment]
Cheers mate, I agree with you, that would be a lot easier as a plug and play and especially for people who do not have any programming knowledge
