### ISSUE TITLE
Reason for different json file output sizes and sample quality based on same model?

### ISSUE THREAD

**Issue by GenTxt** [corolla-johnson/mkultra#7]
All notebooks working as specified on ubuntu 18.04 and gpu but I have a question concerning 
the size of the my json output files compared to the provided repo examples.

1. 'neuromancer_gpt2.json' is 410.4 kb and works with default gpt2 model (548 megs)

Size of 'Neuromancer.txt' is approximately 492.6 kb (depending on source)

The output is good for a small text and model.

2. Ran 'tuning_finetune.ipynb' on the above text using gpt-neo 2.7B (10.7 gigs)

Final 'neuromancer-cyclic-dropout-2-gpt-neo-2.7B-step-240.json' is only 314.8 kb (with 662.2 kb 'tokens.json' file)

The output via 'text_generation.ipynb' is ok but not as good. 

3. I've tested current and recommended 'Adafactor hyperparameters' and the .json file sizes remain the same.

4. Attempted to recreate size and quality of the provided 'neuromancer_gpt2.json' (410.4 kb) with gpt2 small 
but the final json size is only 95 kb (???)

The sampled text isn't as good as the original.

Am I missing a step here? The notebook should reproduce a similar json using the same model?

Would appreciate clarification.

**Comment by vfbd** [comment]
The physical size of the resulting JSON is approximately proportional to the product of the number of tokens in your initial prompt and the embedding dimension of your model (which can be found in your model's config.json as either `n_embd` or `hidden_size`, depending on the specific type of model). You need to choose a good initial prompt to get good quality.

**Comment by GenTxt** [comment]
Thanks for the quick reply.

Above is understood regarding prompt quality but it doesn't explain why the supplied ''neuromancer_gpt2.json'  based on gpt2 small is 410.4kb while my generated .json using the **same** text, model, and code is only 95kb or why using gpt-neo 2.7B only produces a 314.8kb json ?

BTW: Just generated another json @ 503.3 kb using gpt-j-6B. Not much bigger than the original generated with gpt2

**Comment by vfbd** [comment]
Like I said, the size depends on the number of tokens in the initial prompt. I don't think the initial prompts used for the sample JSONs were given -- you probably didn't use the same ones.

**Comment by GenTxt** [comment]
Ahh, used a long single line 'Initial prompt length: 243 tokens'  and generated 498kb json using gpt2 small.

Longer initial prompt length = larger generated json using the same model.

That's the explanation I was looking for.

Thanks. Closing issue
